version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
    - "3334:3333"
    volumes:
    - /home/ubuntu:/zc
    depends_on: 
    - mongo
    container_name: zc-web
    networks:
    - zcnode
    links:
    - mongo
    restart: always
    stdin_open: true
    tty: true
  mongo:
    image: mongo
    ports:
    - "27018:27017"
    volumes:
    - /data/db:/data/db
    networks:
    - zcnode
    container_name: zc-db
networks:
   zcnode:
    driver: bridge